// Consignee Name → Correct Platform Name mapping
// Source: Platform Right Name.xlsx reference sheet
const CONSIGNEE_TO_PLATFORM = {
  'Emiza': 'Emiza',
  'GUNJAN SALES': 'Gunjan Sales',
  'Hands on trade': 'Blinkit',
  'Shree ji food': 'Shreeji Foods',
  'Landcraft': 'Landcraft Retail',
  'Sridevi agencies': 'SRIDEVI AGENCIES',
  'Supermarket': 'Super Market',
  'Innovative': 'Big Basket',
  'FORGREEN FOODS': 'FORGREEN FOODS',
  'ITHIKI TECHNOLOGIES PRIVATE LIMITED': 'ITHIKI',
  'GRAMEENA KARAKUSHALA UDYAMA': 'Grameena Angadi',
  'ANVESHAN FARM TECHNOLOGIES PRIVATE LIMITED': 'Emiza',
  'SRISHTI TRADERS AND ICE CREAM PARLOUR': 'SRISHTI TRADERS',
  'Haiko supermarket , dk': 'Super Market',
  'natural basket': 'Reliance',
  'emiza - kolkatta': 'Emiza',
  'Emiza Mumbai': 'Emiza',
  'SUPERMARKET GROCERY SUPPLIES PRIVATE LIMITED': 'Super Market',
  'GHODAWAT RETAIL PRIVATE LIMITED,': 'Retail Other',
  'MS SRIDEVI AGENCIES': 'SRIDEVI AGENCIES',
  'Prozo': 'Prozo',
  'Gujan sales': 'Gunjan Sales',
  'HOT- RTV': 'Blinkit',
  'INNOMEX INTERNATIONAL': 'Retail Other',
  'HOT': 'Blinkit',
  'Anveshan Farm Technologies Private Limited Manesar': 'Emiza',
  'Ajit': 'Shopify Other',
  'control print ltd - nalagerh': 'Control Print',
  'Grameena AngadiBengaluru': 'Grameena Angadi',
  'Reliance': 'Reliance',
  'Anveshan': 'Emiza',
  'Anveshan Prozo Bangalore Warehouse': 'Prozo',
  'Shreeji Foods CST': 'Shreeji Foods',
  'Rahul Gupta': 'Shopify Other',
  'Anveshan Farm Technologies': 'Emiza',
  'Zepto': 'Zepto',
  'V S NATURAL AGRO FOODS': 'V S Naturals',
  'Prozo greater thane pickup': 'Prozo',
  'Zepto Private Limited Tamil Nadu': 'Zepto',
  'Anveshan Prozo Bhiwandi Warehouse': 'Prozo',
  'Landcraft Retail Pvt Ltd FOOD SQUARE WORLI': 'Landcraft Retail',
  'Deepak Jain': 'Shopify Other',
  'FIRSTCLUB TECHNOLOGY PRIVATE LIMITEDKA': 'FIRSTCLUB',
  'shreeji food Cst, vs': 'Shreeji Foods',
  'SPECTRUM DISTRIBUTORS': 'SPECTRUM DISTRIBUTORS',
  'Foxtrot Outsourcing and Technologies Private limited': 'Shopify Other',
  'Shristhi': 'Retail Other',
  'Shree je food': 'Shreeji Foods',
  'peozo': 'Prozo',
  'Shree food': 'Shreeji Foods',
  'Landcraft Retail Pvt Ltd Food Square': 'Landcraft Retail',
  'Anveshan Prozo Bhiwandi Warehouse prozo integrated logistics private limited': 'Prozo',
  'Sridevi': 'SRIDEVI AGENCIES',
  'BLINK COMMERCE PRIVATE LIMITED Pune P': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITED Faridabad Feeder': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDAP': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITED': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDTL': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITED Bengaluru B': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDUP': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDGJ': 'Blinkit',
  'Zepto Limited Haryana': 'Zepto',
  'BLINK COMMERCE PRIVATE LIMITEDMH': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDBihar': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDAssam': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDKundli Feeder': 'Blinkit',
  'BLINK COMMERCE PRIVATE LIMITEDTN': 'Blinkit',
  'Consignee': 'Retail Other',
  'Kiranakart': 'Zepto',
  'Scootsy': 'Swiggy',
  'Ritika': 'Shopify Other',
  'Amazon - MAA4': 'FBA',
  'Amazon - AMD2': 'FBA',
  'Amazon - HYD8': 'FBA',
  'Amazon - BLR7': 'FBA',
  'Amazon - LKO1': 'FBA',
  'Amazon - CCX2': 'FBA',
  'Amazon - BOM7': 'FBA',
  'Aira Dairy': 'Aira Dairy',
  'Srevee Edible': 'Srevee Edible',
  'Amazon - ATX1': 'FBA',
  'Amazon - CCX1': 'FBA',
  'Amazon - CJBT1': 'FBA',
  'Amazon - JPX2': 'FBA',
  'Amazon - HBL4': 'ARIPL',
  'Amazon - HMH4': 'ARIPL',
  'Amazon - HCC2': 'ARIPL',
  'Amazon - BOM5': 'FBA',
  'Control Print': 'Control Print',
  'Amazon - DED5': 'ARIPL',
  'Sagar Chhabara': 'Shopify Other',
  'Amazon - HDL2': 'ARIPL',
  'FK': 'FK Minutes',
  'Ithiki Technologies': 'ITHIKI',
  'Work Villa (Anees)': 'Retail Other',
  'Amazon - HKA2': 'ARIPL',
  'Anand Trivedi': 'Shopify Other',
  'Nithin BS': 'ITHIKI',
  'Aerotek Nxtgen': 'Retail Other',
  'Amazon': 'FBA',
  'Landcraft Retail': 'Landcraft Retail',
  'Amazon - BLR8': 'FBA',
  'Amazon - HHR7': 'ARIPL',
  'First Club Tech.': 'FIRSTCLUB',
  'Amazon - DEL5': 'FBA',
  'Amazon - HMU5': 'ARIPL',
  'Grameena Angadi': 'Grameena Angadi',
  'Aira Dairy (Anees)': 'Aira Dairy',
  'Amazon - DEL4': 'FBA',
  'Reliance Retail': 'Reliance',
  'Mayur Shetty': 'Shopify Other',
  'Shree Ji Foods': 'Shreeji Foods',
  'Amazon - BLR4': 'ARIPL',
  'Amazon - ISK3': 'ARIPL',
  'Amazon - DED3': 'ARIPL',
  'Sumera Khwaja': 'Shopify Other',
  'Amazon - HBA4': 'ARIPL',
  'Amazon - HNR4': 'ARIPL',
  'Avenue': 'D Mart',
  'Firstclub Technologies': 'FIRSTCLUB',
  'Srishti': 'SRISHTI TRADERS',
  'Indospace': 'Retail Other',
  'Amazon - HKA5': 'ARIPL',
  'Starlaw Partners': 'Shopify Other',
  'Culinary Culture': 'Retail Other',
  'Everstone Capital': 'Everstone Capital',
  'Indospace Capital': 'Retail Other',
  'Everyone Capital': 'Everstone Capital',
  'Vesashree': 'Shopify Other',
  'Divneet Sethi': 'Shopify Other',
  'Bharat Jain': 'Shopify Other',
  'Nilesh Shah': 'Shopify Other',
  'Abhishek': 'Shopify Other',
  'Pawan Kumar': 'Shopify Other',
  'Amazon - HYD3': 'FBA',
  'Amazon - PNQ3': 'FBA',
  'Vandana Makkar': 'Shopify Other',
  'Flagship': 'Shopify Other',
  'Srinidi Innani': 'Shopify Other',
  'Jyoti': 'Shopify Other',
  'APAV Healthcare': 'Shopify Other',
  'Vedashree': 'Shopify Other',
  'Priyanshi Modh': 'Shopify Other',
  'Prateek': 'Shopify Other',
  'V S Natural': 'V S Naturals',
  'Dhrumil': 'Shopify Other',
  'Sheetu Gumer': 'Shopify Other',
  'V S Naturals': 'V S Naturals',
  'Sivu': 'Shopify Other',
  'First Club Technologies': 'FIRSTCLUB',
  'Swastha Foods': 'Retail Other',
  'Rajni Trivedi': 'Shopify Other',
  'Kapil Chogga': 'Shopify Other',
  'Moti Samsukha': 'Shopify Other',
  'Sheela Agarwal': 'Shopify Other',
  'Raghabendra Sahoo': 'Shopify Other',
  'Dhruv': 'Shopify Other',
  'Shri Veera Kumar Industry': 'Retail Other',
  'First Club': 'FIRSTCLUB',
  'Ram Janam Rai': 'Shopify Other',
  'Kailash Industries': 'Shopify Other',
  'Vinay': 'Shopify Other',
  'Rukhsana Ali': 'Shopify Other',
  'Harsh Tibewal': 'Shopify Other',
  'Shamim Ahmed': 'Shopify Other',
  'Amazon - HCC5': 'ARIPL',
  'Innovative Cafes': 'HoReCa',
  'Amit Metals': 'Amit Metals',
  'Srevee Edibles': 'Srevee Edible',
  'Amazon - HPN6': 'ARIPL',
  'Amazon - HHYT': 'ARIPL',
  'Chirag Tuli': 'Shopify Other',
  'Fathima K': 'Shopify Other',
  'Manish Tiwari': 'Shopify Other',
  'Amit Mishra': 'Amit Metals',
  'Zuhaib': 'Shopify Other',
  'Godesi Mandi': 'Retail Other',
  'Jio Mart': 'Reliance',
  'Amazon - HHY7': 'ARIPL',
  'Dhanya': 'Shopify Other',
  'Satish': 'Shopify Other',
  'Amita Vecha': 'Shopify Other',
  'Mahesh': 'Shopify Other',
  'Charu': 'Shopify Other',
  'Karan Narang': 'Shopify Other',
  'Bikash Parida': 'Shopify Other',
  'Ashu Phull': 'Shopify Other',
  'Innovative Restaurant': 'HoReCa',
  'Ithiki': 'ITHIKI',
  'V S Natural Agro': 'V S Naturals',
  'Amazon - HCI2': 'ARIPL',
  'Spectrom': 'SPECTRUM DISTRIBUTORS',
  'Amazon - HCC6': 'ARIPL',
  '2M Nutri Foods': 'Retail Other',
  'VS Naturals': 'V S Naturals',
  'Dhampure Speciality Sugars': 'Shopify Other',
  'Gir Gavdi Dairy Farm': 'Gir Gavdi Dairy',
  'Shneha Daryani': 'Shopify Other',
  'Heena Gidwani': 'Shopify Other',
  'Shrishti Traders': 'Retail Other',
  'Spectrum': 'SPECTRUM DISTRIBUTORS',
  'Kalyan Padgha': 'Prozo',
  'Hands on Traders': 'Blinkit',
  'Kirana Kart': 'Zepto',
  'Scooty': 'Swiggy',
  'Ashok kamra, ivc': 'Shopify Other',
  'Jenish kabutarwala , kh viv': 'Shopify Other',
  'Srishti Traders': 'SRISHTI TRADERS',
  'nahar logistics , ravi': 'Retail Other',
  'White Stone': 'Retail Other',
  'Rainwaers 4u, Amrita jain': 'Retail Other',
  'NA': 'Shopify Other',
  'Haiko Distributor': 'Retail Other',
  'TWENTY LIFESTYLE LLP': 'Blinkit',
  'ayurising wellness llp , k': 'Shopify Other',
  'Flipkart': 'FK Minutes',
  'SURVEY NO 952 AND 41': 'Retail Other',
  'MYLAPURA VILLAGE JADEGE': 'Shopify Other',
  'A V LOGISTICS': 'Retail Other',
  'PLOT NO RS 1852185358': 'Shopify Other',
  'SURVEY NO 95/2': 'Retail Other',
  'APEEJAY GLOBAL LOGISTICS PARK': 'Shopify Other',
  'KHET NO 61 HABIBRPUR GRATER': 'Shopify Other',
  'MYLAPURA VILLAGE JADEGENDHALLOI HOBLI': 'Shopify Other',
  'KAYALNI EXPRESWAY MOHISPOTA NEAR': 'Shopify Other',
  'GATE NO 106/2 VILLAGE SATE': 'Shopify Other',
  'GAT NO 43/1 P AND 46-P': 'Shopify Other',
  'NO 48849 SOUKYA RAOD': 'Shopify Other',
  'MH NLM DRY BLR 100/1B': 'Shopify Other',
  'SY NO 518 KISTAPUR VILLAGE': 'Retail Other',
  'SHOP NO 51 PURAMSAN': 'Shopify Other',
  'GGN BILASPUR MOTHERHUB': 'Prozo',
  'SURVEY NO 45/A/2': 'Retail Other',
  'SURVEY NO 95/2 AND 4/1': 'Retail Other',
  'Huber Suhner Eloctronics, jj': 'Retail Other',
  'Roshini': 'Shopify Other',
  'Survey No. 91/1B2, Survey': 'Retail Other',
  'Khasra, Khasra': 'Shopify Other',
  'GGNBilaspur Motherhub, Gurugram, GGNBilaspur Motherhub Gurugram': 'Prozo',
  'Khasra No. 18//25/2min, Khasra': 'Shopify Other',
  'MH-DRY-LKO MOHANLAL, MHDRYLKO MOHANLAL': 'Zepto',
  'Ratan Logistics Hub, Ratan Logistics Hub': 'Retail Other',
  'Dr. Goyal, anil': 'Shopify Other',
  'Brijesh Vissanji, Brijesh': 'Shopify Other',
  'Joshino Fetnandas , Josonho': 'Shopify Other',
  'Dushyantt Singh': 'Shopify Other',
  'Super market': 'Super Market',
  'Ajay Mahajan, ajay': 'Shopify Other',
  'Sardar Traders': 'Shopify Other',
  'supermarket grocessery': 'Super Market',
  'raja seth, gh': 'Shopify Other',
  'capital , Pardeep': 'Shopify Other',
  'FIRSTCLUB TECHNOLOGY PRIVATE LIMITED': 'FIRSTCLUB',
  'Flipkart India Private Limited': 'FK Minutes',
  'Flipkart India Pvt. Ltd. Minutes': 'FK Minutes',
  'Rainwears': 'Retail Other',
  'Zepto Private Limited': 'Zepto',
  'Landcraft retail pvt,ltd,, jv incv': 'Landcraft Retail',
  'Avenue ECommerce Ltd': 'D Mart',
  'Avenue E commerce': 'D Mart',
  'Avenue E commerce ltd': 'D Mart',
  'Hands On Trades': 'Blinkit',
  'Emiza Supply Chain Services Pvt Ltd': 'Emiza',
};

// Build case-insensitive lookup for better matching
const CASE_INSENSITIVE_MAP = {};
for (const [key, value] of Object.entries(CONSIGNEE_TO_PLATFORM)) {
  CASE_INSENSITIVE_MAP[key.toLowerCase().trim()] = value;
}

export function correctPlatformName(consigneeName) {
  if (!consigneeName) return consigneeName;
  const trimmed = consigneeName.trim();
  // Try exact match first, then case-insensitive
  return CONSIGNEE_TO_PLATFORM[trimmed] || CASE_INSENSITIVE_MAP[trimmed.toLowerCase()] || trimmed;
}

export default CONSIGNEE_TO_PLATFORM;
